### ISSUE TITLE
is it wrong?

### ISSUE THREAD

**Issue by UncleJey** [GunshipPenguin/nescafe#5]
// Sprite evaluation starts at the current OAM address and goes to the end of OAM (256 bytes)
            for (int i = _oamAddr; i < (256 - _oamAddr); i += 4)

hi!
can't understand this line
why (256 - _oamAddr)?
may be it should
 for (int i = _oamAddr; i < 256; i += 4)

**Comment by GunshipPenguin** [comment]
Hi there,

Yes, this appears to be a mistake on my part when I was implementing sprite evaluation. 13876b8816933d3c54f38560510cd62a997ddd31 fixes it.

Thanks for catching this bug!
